"""
Pydantic models for requests and responses.
"""

from pydantic import BaseModel, Field


# Request models
class OAuthAuthorizeRequest(BaseModel):
    """Request to start OAuth flow."""

    code_verifier: str = Field(
        ..., description="PKCE code verifier generated by the client"
    )
    redirect_uri: str = Field(
        ..., description="OAuth redirect URI (can be custom scheme for mobile apps)"
    )
    state: str | None = Field(None, description="State for CSRF validation")


class OAuthTokenRequest(BaseModel):
    """Request to exchange code for token."""

    code: str = Field(..., description="Authorization code")
    code_verifier: str = Field(..., description="PKCE code verifier")
    state: str | None = Field(None, description="State for validation")


class OAuthRefreshRequest(BaseModel):
    """Request to refresh access token."""

    refresh_token: str = Field(..., description="Refresh token")


class OAuthRevokeRequest(BaseModel):
    """Request to revoke token."""

    token: str = Field(..., description="Token to revoke")


# Response models
class OAuthAuthorizeResponse(BaseModel):
    """Response with authorization URL."""

    authorization_url: str = Field(..., description="OAuth authorization URL")
    state: str = Field(..., description="State for validation")


class OAuthTokenResponse(BaseModel):
    """Response with access tokens."""

    access_token: str = Field(..., description="Access token")
    refresh_token: str | None = Field(None, description="Refresh token")
    expires_in: int = Field(..., description="Expiration time in seconds")
    token_type: str = Field(default="Bearer", description="Token type")


class OAuthRevokeResponse(BaseModel):
    """Token revocation response."""

    success: bool = Field(..., description="Whether revocation was successful")
    message: str | None = Field(None, description="Additional message")


class HealthResponse(BaseModel):
    """Health check response."""

    status: str = Field(default="ok", description="Service status")
    version: str = Field(..., description="Backend version")


class ErrorResponse(BaseModel):
    """Error response."""

    error: str = Field(..., description="Error type")
    message: str = Field(..., description="Error message")
    details: dict | None = Field(None, description="Additional details")
