"""Request models for device attestation endpoints."""

# datetime and timezone were unused
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from apuntador.api.v1.device.attestation.constants import (
    DEVICE_ID_DESCRIPTION,
    DEVICE_ID_PATTERN,
)


class AttestationPlatform(str, Enum):
    """Supported attestation platforms."""

    ANDROID = "android"
    IOS = "ios"
    DESKTOP = "desktop"


class SafetyNetAttestationRequest(BaseModel):
    """Request model for SafetyNet attestation verification.

    The JWS (JSON Web Signature) token is received from the Android device
    after calling the SafetyNet Attestation API.
    """

    jws_token: str = Field(
        ...,
        description="SafetyNet attestation JWS token from Android device",
        min_length=100,
    )
    device_id: str = Field(
        ...,
        description=DEVICE_ID_DESCRIPTION,
        pattern=DEVICE_ID_PATTERN,
    )
    nonce: str = Field(
        ...,
        description="Nonce used in attestation request (base64 encoded)",
        min_length=16,
    )


class DeviceCheckAttestationRequest(BaseModel):
    """Request model for iOS DeviceCheck attestation verification.

    The device_token is a one-time token generated by DeviceCheck framework.
    """

    device_token: str = Field(
        ...,
        description="DeviceCheck device token from iOS device",
        min_length=100,
    )
    device_id: str = Field(
        ...,
        description=DEVICE_ID_DESCRIPTION,
        pattern=DEVICE_ID_PATTERN,
    )
    challenge: str = Field(
        ..., description="Challenge string used in attestation request", min_length=16
    )


class DesktopAttestationRequest(BaseModel):
    """Request model for desktop device attestation.

    Desktop platforms don't have hardware-backed attestation,
    so we use device fingerprinting and rate limiting.
    """

    device_id: str = Field(
        ...,
        description=DEVICE_ID_DESCRIPTION,
        pattern=DEVICE_ID_PATTERN,
    )
    fingerprint: str = Field(
        ...,
        description="Device fingerprint (hash of hardware info)",
        pattern=r"^[a-f0-9]{64}$",  # SHA-256 hex
    )
    platform_details: dict[str, Any] = Field(
        ...,
        description="Platform details (OS, arch, hostname, etc.)",
    )


class AttestationVerificationRequest(BaseModel):
    """Generic attestation verification request.

    This model is used when the platform is known and the appropriate
    platform-specific data is provided.
    """

    platform: AttestationPlatform = Field(
        ..., description="Platform type (android/ios/desktop)"
    )
    device_id: str = Field(
        ...,
        description="Unique device identifier",
        pattern=r"^[a-zA-Z0-9_-]{8,64}$",
    )
    attestation_data: dict[str, Any] = Field(
        ...,
        description="Platform-specific attestation data (JWS token, device token, or fingerprint)",
    )


__all__ = [
    "AttestationPlatform",
    "SafetyNetAttestationRequest",
    "DeviceCheckAttestationRequest",
    "DesktopAttestationRequest",
    "AttestationVerificationRequest",
]
