"""OAuth Request Models."""

from pydantic import BaseModel, Field


class OAuthAuthorizeRequest(BaseModel):
    """Request to start OAuth flow."""

    code_verifier: str = Field(
        ..., description="PKCE code verifier generated by the client"
    )
    redirect_uri: str = Field(
        ..., description="OAuth redirect URI (can be custom scheme for mobile apps)"
    )
    state: str | None = Field(None, description="State for CSRF validation")


class OAuthTokenRequest(BaseModel):
    """Request to exchange code for token."""

    code: str = Field(..., description="Authorization code")
    code_verifier: str = Field(..., description="PKCE code verifier")
    state: str | None = Field(None, description="State for validation")


class OAuthRefreshRequest(BaseModel):
    """Request to refresh access token."""

    refresh_token: str = Field(..., description="Refresh token")


class OAuthRevokeRequest(BaseModel):
    """Request to revoke token."""

    token: str = Field(..., description="Token to revoke")
